# Generated by Django 6.0.4 on 2026-05-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('indexing', 'Indexing'), ('cloning', 'Cloning'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('local_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
